In [1]:
import numpy as np

In [4]:
arr1=np.random.randint(1,40,(5,4))
arr1

array([[33, 37, 27, 15],
       [25, 22, 29, 33],
       [36, 21, 36,  9],
       [16, 35, 25,  8],
       [21, 24, 25, 34]])

In [7]:
a=arr1[3][3]
a

8

In [17]:
arr1[3:5,1:3]


array([[35, 25],
       [24, 25]])

In [19]:
arr1[:,:3]

array([[33, 37, 27],
       [25, 22, 29],
       [36, 21, 36],
       [16, 35, 25],
       [21, 24, 25]])

In [20]:
arr1[:2,:]

array([[33, 37, 27, 15],
       [25, 22, 29, 33]])

In [21]:
arr1[:,1:3]

array([[37, 27],
       [22, 29],
       [21, 36],
       [35, 25],
       [24, 25]])

In [22]:
arr1[:3,:3]

array([[33, 37, 27],
       [25, 22, 29],
       [36, 21, 36]])

In [26]:
print(arr1[::2,:],"\n")
print(arr1)

[[33 37 27 15]
 [36 21 36  9]
 [21 24 25 34]] 

[[33 37 27 15]
 [25 22 29 33]
 [36 21 36  9]
 [16 35 25  8]
 [21 24 25 34]]
